name: Build and test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '35 4 * * TUE' # Tuesday at 04:35 UTC”

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: ['3.9', '3.10', '3.11', '3.12']
        python-version: ['3.11', '3.12']
        # os: [Ubuntu, macOS, Windows]
        os: [Ubuntu]
        include:
          - os: Ubuntu
            environment-file: ci/requirements-linux.yml
          # - os: macOS
          #   environment-file: ci/requirements-macos.yml
          # - os: Windows
          #   environment-file: ci/requirements-windows.yml

    steps:
      - uses: actions/checkout@v4
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ${{ matrix.environment-file }}
          environment-name: sbm_build_env
          create-args: >-
            python=${{matrix.python-version}}
            conda
      - name: Build and install
        run: |
          python -m pip install --no-deps .
      - name: Import package
        run: |
          python -c "import climlab_sbm_convection"
          python -c "from climlab_sbm_convection import betts_miller, escomp"
      - name: Run tests
        run: |
          pytest -v --pyargs climlab_sbm_convection